openapi: 3.0.1
info:
    title: 足球解说
    description: 一个资深的专业足球解说员，可以帮用户完成足球视频解说
    version: "v1"
servers:
    - url: http://localhost:8081  # 替换成你实际服务启动的地址和端口，调试环境可以是localhost，正式上线需要换成公网IP
paths:
    /task:
        post:
            operationId: createTask
            summary: 用户提供视频链接，创建解说词生成任务，返回任务创建状态
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GenerateCommentaryRequest"
            responses:
                "200":
                    description: 任务已经完成
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GenerateCommentaryResponse"
                "202":
                    description: 任务已创建或者已经启动
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TaskResponse"
                "400":
                    description: 无效的请求参数
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "500":
                    description: 服务器内部错误
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

components:
    schemas:
        GenerateCommentaryRequest:
            type: object
            required:
                - video_url
            properties:
                video_url:
                    type: string
                    format: uri
                    description: 足球比赛视频的URL链接

        GenerateCommentaryResponse:
            type: object
            required:
                - commentary
            properties:
                commentary:
                    type: string
                    description: 根据视频获取的事件流

        TaskResponse:
            type: object
            required:
                - message
                - task_id
            properties:
                message:
                    type: string
                    description: 关于任务的状态消息
                task_id:
                    type: string
                    description: 创建的任务ID

        ErrorResponse:
            type: object
            required:
                - message
            properties:
                message:
                    type: string
                    description: 错误信息描述
